services:
  api:
    image: "${IMAGEN_API}"
    environment:
      - PUERTO_NESTJS=${PUERTO_NEST}
    ports:
      - "8000:${PUERTO_NEST}"

  db:
    image: "mysql:${VERSION_DB}"
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "5601:3306"